baseURL = "https://paalpe.github.io/P-A-L-S/"
languageCode = "en-us"
title = "PAL-S*"
theme = "paper"


#disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  #twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'paalpe'                 # github.com/YOUR_GITHUB_ID
  instagram = 'paalspedersen'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'palped'             # linkedin.com/in/YOUR_LINKEDIN_ID
  #mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'


  # home page profile
  avatar = 'https://file.notion.so/f/f/f084bc39-5206-4589-b3f1-e5326b056471/e2fe8664-16ba-4ba1-9e99-792b35ce8377/paalspedersen.jpg?id=30abee98-e994-4010-ad5d-e2477b97f2e4&table=block&spaceId=f084bc39-5206-4589-b3f1-e5326b056471&expirationTimestamp=1704326400000&signature=w5JRc-KJGRligttJwJZp_fXEkIfpIbPcTzCNmgkSsmo&downloadName=paalspedersen.jpg'                 # gravatar email or image url
  name = 'Pål Sørvik Pedersen'
  bio = "My name is Pål and this is a blog i'm working on"


  # misc
  #disableHLJS = true                        # disable highlight.js
  ##disablePostNavigation = true              # disable post navigation
  ##monoDarkIcon = true                       # show monochrome dark mode icon
  ##gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  ##graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                           # enable KaTeX math typesetting globally

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10