baseURL = "https://www.pal-s.no/"
languageCode = "en-us"
title = "PAL-S*"
theme = "paper"


#disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  #twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'paalpe'                 # github.com/YOUR_GITHUB_ID
  instagram = 'paalspedersen'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'palped'             # linkedin.com/in/YOUR_LINKEDIN_ID
  #mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'


  # home page profile
  avatar = 'https://tjpstyjkg4nucxxg.public.blob.vercel-storage.com/paal-sorvik-pedersen-profile-ruwslymkP92XZl1hpKLBHRM8yXQUIo.webp'                 # gravatar email or image url
  name = 'Pål Sørvik Pedersen'
  bio = "Notes, articles, and experiences gathered along the way of a business developer with a passion for technology"


  # misc
  #disableHLJS = true                        # disable highlight.js
  ##disablePostNavigation = true              # disable post navigation
  ##monoDarkIcon = true                       # show monochrome dark mode icon
  ##gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  ##graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  ##math = true                           # enable KaTeX math typesetting globally

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
 ## [[menu.main]]
 ##   identifier = "contact"
 ##   name = "Contact"
 ##   url = "/contact/"
 ##   weight = 10